bonus_gui_ordering =
{
  ["character"] = "a",
  ["inserter"] = "b",
  ["stack_inserter"] = "c",
  ["mining_productivity"] = "d",
  ["follower_robots"] = "e",
  ["train_braking_force"] = "f",
  ["research_speed"] = "g",
  ["worker_robots"] = "h",
  ["turret_attack"] = "i",
  ["laser"] = "j",
  ["artillery_range"] = "k",
  ["bullet"] = "l",
  ["flamethrower"] = "m",
  ["artillery-shell"] = "o",
  ["shotgun-shell"] = "p",
  ["cannon-shell"] = "q",
  ["beam"] = "r",
  ["grenade"] = "s",
  ["landmine"] = "t",
  ["rocket"] = "u",
  ["electric"] = "v",
  ["capsule"] = "x",
  ["melee"] = "y",
  ["biological"] = "z"
  }
